version: '2'
volumes:
  drupal_data:
  drupal_ssh:
  drupal_solr:
services:
  web:
    build: .
    ports:
      - "80:80"
      - "81:81"
      - "9000:9000"
      - "443:443"
      - "8025:8025"
      - "49100:22"
    extra_hosts:
      - "docker.local:127.0.0.1"
    links:
      - database
      - memcached
    volumes:
      - /var/www/experiment/:/var/www/html/
    environment:
      - TERM=xterm
  database:
    image: mysql:5
    ports:
      - "3306:3306"
    volumes:
      - ./docker-utils/mysql/conf.d:/etc/mysql/conf.d
      - drupal_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: drupal
  memcached:
    image: memcached
    ports:
      - "11211:11211"
  solr:
    image: solr:5.5.4
    ports:
     - "8983:8983"
    volumes:
      - drupal_solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
